// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/sterligov/otus_homework/hw12_13_14_15_calendar/internal/config"
	"github.com/sterligov/otus_homework/hw12_13_14_15_calendar/internal/rabbitmq"
	"github.com/sterligov/otus_homework/hw12_13_14_15_calendar/internal/sender"
)

// Injectors from wire.go:

func setup(configConfig *config.Config) (*sender.Sender, func(), error) {
	rabbit := rabbitmq.NewRabbit(configConfig)
	senderSender := sender.NewSender(rabbit)
	return senderSender, func() {
	}, nil
}
