// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/sterligov/otus_homework/hw12_13_14_15_calendar/internal/config"
	"github.com/sterligov/otus_homework/hw12_13_14_15_calendar/internal/server/http"
	"github.com/sterligov/otus_homework/hw12_13_14_15_calendar/internal/storage/factory"
	"github.com/sterligov/otus_homework/hw12_13_14_15_calendar/internal/storage/sql"
	"github.com/sterligov/otus_homework/hw12_13_14_15_calendar/internal/usecase/calendar"
)

// Injectors from wire.go:

func setup(configConfig *config.Config) (*internalhttp.Server, func(), error) {
	db, cleanup, err := sqlstorage.DatabaseProvider(configConfig)
	if err != nil {
		return nil, nil, err
	}
	eventRepository, err := factory.CreateEventRepository(configConfig, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	eventUseCase := calendar.NewEventUseCase(eventRepository)
	handler := internalhttp.NewHandler(eventUseCase)
	server, err := internalhttp.NewServer(configConfig, handler)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup()
	}, nil
}
