version: "3"

services:
  calendar-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./calendar/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./calendar/mysql/data:/var/lib/mysql
    ports:
      - "3311:3306"
