logger:
  level: info
  path: stderr

http:
  addr: :8081
  write_timeout: 5s
  read_timeout: 5s
  handler_timeout: 5s

grpc:
  addr: :8082

database:
  connection_addr: calendar_user:calendar_pass@tcp(calendar_db:3306)/calendar?parseTime=true
  driver: mysql
  max_open_conns: 20
  max_idle_conns: 20
  max_conn_lifetime: 5m

storage_type: sql
