// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	storage "github.com/sterligov/otus_homework/hw12_13_14_15_calendar/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// EventRepository is an autogenerated mock type for the EventRepository type
type EventRepository struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: ctx, event
func (_m *EventRepository) CreateEvent(ctx context.Context, event storage.Event) (storage.EventID, error) {
	ret := _m.Called(ctx, event)

	var r0 storage.EventID
	if rf, ok := ret.Get(0).(func(context.Context, storage.Event) storage.EventID); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(storage.EventID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, storage.Event) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEvent provides a mock function with given fields: ctx, id
func (_m *EventRepository) DeleteEvent(ctx context.Context, id storage.EventID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.EventID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEventByID provides a mock function with given fields: ctx, id
func (_m *EventRepository) GetEventByID(ctx context.Context, id storage.EventID) (storage.Event, error) {
	ret := _m.Called(ctx, id)

	var r0 storage.Event
	if rf, ok := ret.Get(0).(func(context.Context, storage.EventID) storage.Event); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(storage.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, storage.EventID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserEventsByPeriod provides a mock function with given fields: ctx, uid, start, end
func (_m *EventRepository) GetUserEventsByPeriod(ctx context.Context, uid storage.UserID, start time.Time, end time.Time) ([]storage.Event, error) {
	ret := _m.Called(ctx, uid, start, end)

	var r0 []storage.Event
	if rf, ok := ret.Get(0).(func(context.Context, storage.UserID, time.Time, time.Time) []storage.Event); ok {
		r0 = rf(ctx, uid, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, storage.UserID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, uid, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEvent provides a mock function with given fields: ctx, event
func (_m *EventRepository) UpdateEvent(ctx context.Context, event storage.Event) error {
	ret := _m.Called(ctx, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
