// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StorageConnection is an autogenerated mock type for the StorageConnection type
type StorageConnection struct {
	mock.Mock
}

// PingContext provides a mock function with given fields: _a0
func (_m *StorageConnection) PingContext(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
